displayName=Loot Origin
author=DegoDani
description=Addon to Loot Tracker, which lets you easily see the origins of your loot. Shift + left mouse button any item, click "Check Origin"
tags=loot,tracker,origin
plugins=com.degodani.lootorigin.LootOriginPlugin